name: randomer
description: Randomer helps to you for generate what do you need
version: 0.0.1
#homepage: https://www.example.com
#author: first <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
